# Multi-stage image for dagu-mcp
# Generated by genproj (docker-container capability, language-aware). Adjust
# for your application.
#
# Stage 1 (build): copies the full source tree, installs dependencies and
# builds the application. Stage 2 (runtime): copies only the build output /
# virtualenv and production dependencies, keeping the final image small.

FROM python:3.11-slim AS build
WORKDIR /app
COPY README.md pyproject.toml* requirements.txt* ./
RUN python -m venv /opt/venv \
    && /opt/venv/bin/pip install --upgrade pip \
    && mkdir -p src/dagu_mcp && touch src/dagu_mcp/__init__.py \
    && if [ -f requirements.txt ]; then \
         grep -vE '^\s*(-e|--editable)\s+\.' requirements.txt > /tmp/reqs.txt || true; \
         [ -s /tmp/reqs.txt ] && /opt/venv/bin/pip install --no-cache-dir -r /tmp/reqs.txt; \
       fi \
    && if [ -f pyproject.toml ]; then \
         /opt/venv/bin/pip install --no-cache-dir .; \
       fi
COPY . .
RUN if [ -f requirements.txt ]; then \
      /opt/venv/bin/pip install --no-cache-dir -r requirements.txt; \
    elif [ -f pyproject.toml ]; then \
      /opt/venv/bin/pip install --no-cache-dir --no-deps .; \
    fi

FROM python:3.11-slim
WORKDIR /app
# Link the GHCR container package to its GitHub repo on push. GHCR auto-links
# the package to nickbrett1/dagu-mcp so it inherits the
# repo's access (public repo -> public package; no manual visibility step).
LABEL org.opencontainers.image.source=https://github.com/nickbrett1/dagu-mcp

ENV PATH="/opt/venv/bin:$PATH"
COPY --from=build /opt/venv /opt/venv
COPY . .
EXPOSE 3007


CMD ["python", "-m", "dagu_mcp"]
